"""스프린트와 번다운 (M5)

스프린트는 라벨이 아니라 **기간이 있는 행**이다. 그래야 남은 일을 시간축에
놓을 수 있다.

`sprint_snapshot` 은 그날 값을 그날 적는다. 되짚어 계산하면 나중에 추가된
이슈가 처음부터 있었던 것이 되고, 범위가 늘어난 사실이 그림에서 사라진다.

한 프로젝트에 활성 스프린트는 하나다 — 부분 유니크 인덱스로 DB 가 막는다.


Revision ID: 308fb6926d4a
Revises: 3c0440c4a992
Create Date: 2026-09-08 02:02:19.015302
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "308fb6926d4a"
down_revision: str | None = "3c0440c4a992"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sprint",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("goal", sa.Text(), nullable=True),
        sa.Column("state", sa.String(length=16), nullable=False),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ends_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("activated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "state IN ('future', 'active', 'closed')", name=op.f("ck_sprint_sprint_state")
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["project.id"],
            name=op.f("fk_sprint_project_id_project"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sprint")),
        sa.UniqueConstraint("project_id", "name", name="uq_sprint_project_id_name"),
    )
    op.create_index("ix_sprint_project_id", "sprint", ["project_id"], unique=False)
    op.create_index(
        "uq_sprint_one_active",
        "sprint",
        ["project_id"],
        unique=True,
        postgresql_where=sa.text("state = 'active'"),
    )
    op.create_table(
        "sprint_snapshot",
        sa.Column("sprint_id", sa.Uuid(), nullable=False),
        sa.Column("on_date", sa.Date(), nullable=False),
        sa.Column("remaining_issues", sa.Integer(), nullable=False),
        sa.Column("remaining_minutes", sa.Integer(), nullable=False),
        sa.Column("total_issues", sa.Integer(), nullable=False),
        sa.Column("total_minutes", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["sprint_id"],
            ["sprint.id"],
            name=op.f("fk_sprint_snapshot_sprint_id_sprint"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("sprint_id", "on_date", name=op.f("pk_sprint_snapshot")),
    )
    op.add_column("issue", sa.Column("sprint_id", sa.Uuid(), nullable=True))
    op.create_index("ix_issue_sprint_id", "issue", ["sprint_id"], unique=False)
    op.create_foreign_key(
        op.f("fk_issue_sprint_id_sprint"),
        "issue",
        "sprint",
        ["sprint_id"],
        ["id"],
        ondelete="SET NULL",
    )

    # 보드가 스프린트를 안다.
    #
    # **이미 있던 보드는 `"all"` 로 둔다.** 모델의 기본값은 `"active"` 지만,
    # 그건 *새로* 만드는 보드 이야기다. 어제까지 보이던 카드가 오늘 아침에
    # 사라지면 그건 기능이 아니라 사고다 — 켜는 것은 사람이 한다.
    op.add_column(
        "board",
        sa.Column("sprint_mode", sa.String(length=16), nullable=False, server_default="all"),
    )
    op.create_check_constraint(
        op.f("ck_board_board_sprint_mode"), "board", "sprint_mode IN ('all', 'active')"
    )
    # 서버 기본값은 백필용이다. 앞으로는 모델이 정한다.
    op.alter_column("board", "sprint_mode", server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("ck_board_board_sprint_mode"), "board", type_="check")
    op.drop_column("board", "sprint_mode")
    op.drop_constraint(op.f("fk_issue_sprint_id_sprint"), "issue", type_="foreignkey")
    op.drop_index("ix_issue_sprint_id", table_name="issue")
    op.drop_column("issue", "sprint_id")
    op.drop_table("sprint_snapshot")
    op.drop_index(
        "uq_sprint_one_active", table_name="sprint", postgresql_where=sa.text("state = 'active'")
    )
    op.drop_index("ix_sprint_project_id", table_name="sprint")
    op.drop_table("sprint")
    # ### end Alembic commands ###
