"""search document

Revision ID: 36bd20ecc32d
Revises: ec643c273757
Create Date: 2026-09-06 17:12:57.777053
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "36bd20ecc32d"
down_revision: str | None = "ec643c273757"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "search_document",
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("entity_id", sa.Uuid(), nullable=False),
        sa.Column("scope_kind", sa.String(length=16), nullable=False),
        sa.Column("scope_id", sa.Uuid(), nullable=False),
        sa.Column("ref", sa.String(length=500), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("restricted_to", sa.ARRAY(sa.Uuid()), nullable=True),
        sa.Column("source_updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "kind IN ('issue', 'page')", name=op.f("ck_search_document_search_document_kind")
        ),
        sa.CheckConstraint(
            "scope_kind IN ('project', 'space')",
            name=op.f("ck_search_document_search_document_scope_kind"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_search_document")),
        sa.UniqueConstraint("kind", "entity_id", name="uq_search_document_kind_entity_id"),
    )
    op.create_index(
        "ix_search_document_scope", "search_document", ["scope_kind", "scope_id"], unique=False
    )
    op.create_index(
        "ix_search_document_updated", "search_document", ["source_updated_at"], unique=False
    )
    # ### end Alembic commands ###

    # 한국어 전문검색 인덱스. autogenerate 는 pgroonga 를 만들어 주지 않는다.
    # 제목과 본문을 한 인덱스에 넣어야 `&@~` 가 둘을 한 번에 훑는다.
    op.create_index(
        "ix_search_document_fts",
        "search_document",
        ["title", "body"],
        postgresql_using="pgroonga",
    )


def downgrade() -> None:
    op.drop_index("ix_search_document_fts", table_name="search_document")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_search_document_updated", table_name="search_document")
    op.drop_index("ix_search_document_scope", table_name="search_document")
    op.drop_table("search_document")
    # ### end Alembic commands ###
