"""imported_object — 이관에서 무엇을 이미 옮겼는지 기억한다

이관은 한 번에 끝나지 않는다. 소스가 살아 있는 채로 시작하고, 중간에 멈추고,
며칠 뒤 다시 돌린다. 그때마다 같은 이슈가 새로 만들어지면 옮긴 쪽에 세 벌이
쌓이고 어느 것이 진짜인지 아무도 모른다. 이 표가 두 번째 실행에게 "그건 이미
있다" 를 알려 준다.

**유니크를 DB 에 건다.** 애플리케이션에서만 막으면 두 실행이 동시에 돌 때 둘
다 통과한다 — 관리자가 "안 도는 것 같다" 며 두 번 누르는 것은 흔한 일이다.

열쇠에 `project_id` 가 들어간다. Redmine 두 대에서 각각 1번 이슈를 옮길 수
있고, 같은 Redmine 을 두 프로젝트로 나눠 옮길 수도 있다. `base_url` 은 열쇠에
안 넣었다 — 서버는 이사하고, 주소가 바뀌었다고 같은 이슈가 두 벌이 되면 안 된다.

`target_id` 에 FK 가 없다. 가리키는 표가 종류마다 다르고(이슈·코멘트), 옮긴
이슈를 사람이 지웠을 때 이 기록까지 사라지면 다시 돌릴 때 지운 것이 되살아난다 —
그건 지운 사람이 원한 일이 아니다.

인덱스를 따로 안 만든다. 유니크 제약의 btree 가 `(project_id, source_kind,
target_type, source_id IN (...))` 조회를 그대로 받는다.

Revision ID: 2707d238a528
Revises: f4894494245b
Create Date: 2026-09-12 04:07:21.365151
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "2707d238a528"
down_revision: str | None = "f4894494245b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "imported_object",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("source_kind", sa.String(length=32), nullable=False),
        sa.Column("source_id", sa.String(length=200), nullable=False),
        sa.Column("target_type", sa.String(length=32), nullable=False),
        sa.Column("target_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["project.id"],
            name=op.f("fk_imported_object_project_id_project"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_imported_object")),
        sa.UniqueConstraint(
            "project_id",
            "source_kind",
            "target_type",
            "source_id",
            name="uq_imported_object_identity",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("imported_object")
    # ### end Alembic commands ###
