"""만족도 조사를 보낸 시각 (C11)

한 번만 보내는 근거다. "아직 점수가 없음" 을 근거로 삼으면 답하지 않은
고객이 티켓을 다시 닫을 때마다 또 받는다.


Revision ID: f98a0e89a2c3
Revises: a68ccca0839e
Create Date: 2026-09-07 20:52:10.653498
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "f98a0e89a2c3"
down_revision: str | None = "a68ccca0839e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "ticket_ext", sa.Column("csat_sent_at", sa.DateTime(timezone=True), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("ticket_ext", "csat_sent_at")
    # ### end Alembic commands ###
