"""SCIM 2.0 프로비저닝 (M4)

프로비저닝 토큰은 SSO 설정과 **같은 행**에 둔다: IdP 한 곳이 로그인과 계정
밀어넣기를 함께 담당하고, 그래야 "이 IdP 를 껐다" 가 양쪽에 같이 적용된다.

사용자·그룹에 "누가 밀어 넣었는가" 를 적는다. IdP 가 둘이면 한쪽의 토큰으로
다른 쪽 계정을 비활성화할 수 있으면 안 된다.


Revision ID: 54df8435a606
Revises: f98a0e89a2c3
Create Date: 2026-09-07 21:56:47.233244
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "54df8435a606"
down_revision: str | None = "f98a0e89a2c3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "identity_provider",
        sa.Column("scim_enabled", sa.Boolean(), server_default=sa.text("false"), nullable=False),
    )
    op.add_column(
        "identity_provider", sa.Column("scim_token_hash", sa.String(length=64), nullable=True)
    )
    op.add_column(
        "identity_provider",
        sa.Column("scim_token_issued_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "identity_provider",
        sa.Column("scim_last_seen_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.create_unique_constraint(
        op.f("uq_identity_provider_scim_token_hash"), "identity_provider", ["scim_token_hash"]
    )
    op.add_column("user", sa.Column("scim_provider_id", sa.Uuid(), nullable=True))
    op.add_column("user", sa.Column("scim_external_id", sa.String(length=255), nullable=True))
    op.create_unique_constraint(
        "uq_user_scim_provider_external", "user", ["scim_provider_id", "scim_external_id"]
    )
    op.create_foreign_key(
        op.f("fk_user_scim_provider_id_identity_provider"),
        "user",
        "identity_provider",
        ["scim_provider_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.add_column("user_group", sa.Column("scim_provider_id", sa.Uuid(), nullable=True))
    op.add_column("user_group", sa.Column("scim_external_id", sa.String(length=255), nullable=True))
    op.create_index(
        "ix_user_group_scim_provider_id", "user_group", ["scim_provider_id"], unique=False
    )
    op.create_foreign_key(
        op.f("fk_user_group_scim_provider_id_identity_provider"),
        "user_group",
        "identity_provider",
        ["scim_provider_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_user_group_scim_provider_id_identity_provider"), "user_group", type_="foreignkey"
    )
    op.drop_index("ix_user_group_scim_provider_id", table_name="user_group")
    op.drop_column("user_group", "scim_external_id")
    op.drop_column("user_group", "scim_provider_id")
    op.drop_constraint(
        op.f("fk_user_scim_provider_id_identity_provider"), "user", type_="foreignkey"
    )
    op.drop_constraint("uq_user_scim_provider_external", "user", type_="unique")
    op.drop_column("user", "scim_external_id")
    op.drop_column("user", "scim_provider_id")
    op.drop_constraint(
        op.f("uq_identity_provider_scim_token_hash"), "identity_provider", type_="unique"
    )
    op.drop_column("identity_provider", "scim_last_seen_at")
    op.drop_column("identity_provider", "scim_token_issued_at")
    op.drop_column("identity_provider", "scim_token_hash")
    op.drop_column("identity_provider", "scim_enabled")
    # ### end Alembic commands ###
