"""notify

Revision ID: d6902e43a6a1
Revises: 4fce25dc215a
Create Date: 2026-09-06 09:10:09.389996
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "d6902e43a6a1"
down_revision: str | None = "4fce25dc215a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "notification",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("kind", sa.String(length=64), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("body", sa.Text(), nullable=True),
        sa.Column("link", sa.String(length=500), nullable=True),
        sa.Column("target_type", sa.String(length=32), nullable=True),
        sa.Column("target_id", sa.Uuid(), nullable=True),
        sa.Column("actor_id", sa.Uuid(), nullable=True),
        sa.Column("read_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["actor_id"],
            ["user.id"],
            name=op.f("fk_notification_actor_id_user"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["user.id"], name=op.f("fk_notification_user_id_user"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notification")),
    )
    op.create_index(
        "ix_notification_unread",
        "notification",
        ["user_id", "created_at"],
        unique=False,
        postgresql_where=sa.text("read_at IS NULL"),
    )
    op.create_index(
        "ix_notification_user_created", "notification", ["user_id", "created_at"], unique=False
    )
    op.create_table(
        "notification_preference",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("in_app", sa.Boolean(), nullable=False),
        sa.Column("email", sa.Boolean(), nullable=False),
        sa.Column("notify_own_actions", sa.Boolean(), nullable=False),
        sa.Column("muted_events", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
            name=op.f("fk_notification_preference_user_id_user"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notification_preference")),
        sa.UniqueConstraint("user_id", name=op.f("uq_notification_preference_user_id")),
    )
    op.create_table(
        "watch",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("target_type", sa.String(length=32), nullable=False),
        sa.Column("target_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "target_type IN ('issue', 'project', 'page', 'space')",
            name=op.f("ck_watch_watch_target_type"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["user.id"], name=op.f("fk_watch_user_id_user"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_watch")),
        sa.UniqueConstraint("user_id", "target_type", "target_id", name="uq_watch_user_target"),
    )
    op.create_index("ix_watch_target", "watch", ["target_type", "target_id"], unique=False)
    op.create_table(
        "webhook",
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("scope", sa.String(length=16), nullable=False),
        sa.Column("scope_id", sa.Uuid(), nullable=True),
        sa.Column("url", sa.String(length=2000), nullable=False),
        sa.Column("secret_enc", sa.Text(), nullable=False),
        sa.Column("events", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("consecutive_failures", sa.Integer(), nullable=False),
        sa.Column("disabled_reason", sa.String(length=200), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(scope = 'global') = (scope_id IS NULL)",
            name=op.f("ck_webhook_webhook_scope_id_matches"),
        ),
        sa.CheckConstraint("scope IN ('global', 'project')", name=op.f("ck_webhook_webhook_scope")),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["user.id"],
            name=op.f("fk_webhook_created_by_user"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_webhook")),
    )
    op.create_index(
        "ix_webhook_enabled",
        "webhook",
        ["enabled"],
        unique=False,
        postgresql_where=sa.text("enabled"),
    )
    op.create_index("ix_webhook_scope", "webhook", ["scope", "scope_id"], unique=False)
    op.create_table(
        "webhook_delivery",
        sa.Column("webhook_id", sa.Uuid(), nullable=False),
        sa.Column("event_id", sa.Uuid(), nullable=False),
        sa.Column("event_type", sa.String(length=128), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("attempts", sa.SmallInteger(), nullable=False),
        sa.Column("response_code", sa.Integer(), nullable=True),
        sa.Column("response_excerpt", sa.String(length=1000), nullable=True),
        sa.Column("error", sa.String(length=500), nullable=True),
        sa.Column("next_retry_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("delivered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'delivered', 'failed', 'abandoned')",
            name=op.f("ck_webhook_delivery_webhook_delivery_status"),
        ),
        sa.ForeignKeyConstraint(
            ["webhook_id"],
            ["webhook.id"],
            name=op.f("fk_webhook_delivery_webhook_id_webhook"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_webhook_delivery")),
        sa.UniqueConstraint("webhook_id", "event_id", name="uq_webhook_delivery_event"),
    )
    op.create_index(
        "ix_webhook_delivery_retry",
        "webhook_delivery",
        ["next_retry_at"],
        unique=False,
        postgresql_where=sa.text("status = 'pending'"),
    )
    op.create_index(
        "ix_webhook_delivery_webhook_created",
        "webhook_delivery",
        ["webhook_id", "created_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_webhook_delivery_webhook_created", table_name="webhook_delivery")
    op.drop_index(
        "ix_webhook_delivery_retry",
        table_name="webhook_delivery",
        postgresql_where=sa.text("status = 'pending'"),
    )
    op.drop_table("webhook_delivery")
    op.drop_index("ix_webhook_scope", table_name="webhook")
    op.drop_index("ix_webhook_enabled", table_name="webhook", postgresql_where=sa.text("enabled"))
    op.drop_table("webhook")
    op.drop_index("ix_watch_target", table_name="watch")
    op.drop_table("watch")
    op.drop_table("notification_preference")
    op.drop_index("ix_notification_user_created", table_name="notification")
    op.drop_index(
        "ix_notification_unread",
        table_name="notification",
        postgresql_where=sa.text("read_at IS NULL"),
    )
    op.drop_table("notification")
    # ### end Alembic commands ###
