"""saved filter

Revision ID: 4fce25dc215a
Revises: d3324d645a0f
Create Date: 2026-09-06 08:06:35.395023
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "4fce25dc215a"
down_revision: str | None = "d3324d645a0f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "saved_filter",
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("iql", sa.Text(), nullable=False),
        sa.Column("is_shared", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["user.id"],
            name=op.f("fk_saved_filter_owner_id_user"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_saved_filter")),
        sa.UniqueConstraint("owner_id", "name", name="uq_saved_filter_owner_id_name"),
    )
    op.create_index(
        "ix_saved_filter_shared",
        "saved_filter",
        ["is_shared"],
        unique=False,
        postgresql_where=sa.text("is_shared"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_saved_filter_shared", table_name="saved_filter", postgresql_where=sa.text("is_shared")
    )
    op.drop_table("saved_filter")
    # ### end Alembic commands ###
