"""wiki space and page

Revision ID: ec643c273757
Revises: 1e6a95a2d447
Create Date: 2026-09-06 14:24:57.282772
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "ec643c273757"
down_revision: str | None = "1e6a95a2d447"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "space",
        sa.Column("key", sa.String(length=16), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("home_page_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("kind IN ('team', 'personal', 'kb')", name=op.f("ck_space_space_kind")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_space")),
        sa.UniqueConstraint("key", name=op.f("uq_space_key")),
    )
    op.create_table(
        "page",
        sa.Column("space_id", sa.Uuid(), nullable=False),
        sa.Column("parent_id", sa.Uuid(), nullable=True),
        sa.Column("path", sa.String(length=2000), nullable=False),
        sa.Column("slug", sa.String(length=200), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("current_version_id", sa.Uuid(), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("status IN ('draft', 'published')", name=op.f("ck_page_page_status")),
        sa.ForeignKeyConstraint(
            ["parent_id"], ["page.id"], name=op.f("fk_page_parent_id_page"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["space_id"], ["space.id"], name=op.f("fk_page_space_id_space"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_page")),
    )
    op.create_index("ix_page_parent_id", "page", ["parent_id"], unique=False)
    op.create_index("ix_page_space_id", "page", ["space_id"], unique=False)
    op.create_index("ix_page_space_path", "page", ["space_id", "path"], unique=False)
    op.create_index(
        "uq_page_parent_slug",
        "page",
        ["parent_id", "slug"],
        unique=True,
        postgresql_where=sa.text("parent_id IS NOT NULL"),
    )
    op.create_index(
        "uq_page_space_root_slug",
        "page",
        ["space_id", "slug"],
        unique=True,
        postgresql_where=sa.text("parent_id IS NULL"),
    )
    op.create_table(
        "page_template",
        sa.Column("space_id", sa.Uuid(), nullable=True),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("category", sa.String(length=100), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["space_id"],
            ["space.id"],
            name=op.f("fk_page_template_space_id_space"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_page_template")),
    )
    op.create_index("ix_page_template_space_id", "page_template", ["space_id"], unique=False)
    op.create_table(
        "page_comment",
        sa.Column("page_id", sa.Uuid(), nullable=False),
        sa.Column("author_id", sa.Uuid(), nullable=True),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("anchor", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("anchor_status", sa.String(length=16), nullable=False),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("parent_id", sa.Uuid(), nullable=True),
        sa.Column("edited_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "anchor_status IN ('ok', 'orphaned')",
            name=op.f("ck_page_comment_page_comment_anchor_status"),
        ),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["user.id"],
            name=op.f("fk_page_comment_author_id_user"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["page_id"], ["page.id"], name=op.f("fk_page_comment_page_id_page"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["page_comment.id"],
            name=op.f("fk_page_comment_parent_id_page_comment"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_page_comment")),
    )
    op.create_index("ix_page_comment_page_id", "page_comment", ["page_id"], unique=False)
    op.create_index("ix_page_comment_parent_id", "page_comment", ["parent_id"], unique=False)
    op.create_table(
        "page_label",
        sa.Column("page_id", sa.Uuid(), nullable=False),
        sa.Column("label", sa.String(length=100), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["page_id"], ["page.id"], name=op.f("fk_page_label_page_id_page"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_page_label")),
        sa.UniqueConstraint("page_id", "label", name="uq_page_label_page_id_label"),
    )
    op.create_index("ix_page_label_label", "page_label", ["label"], unique=False)
    op.create_table(
        "page_restriction",
        sa.Column("page_id", sa.Uuid(), nullable=False),
        sa.Column("mode", sa.String(length=8), nullable=False),
        sa.Column("principal_kind", sa.String(length=8), nullable=False),
        sa.Column("principal_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "mode IN ('view', 'edit')", name=op.f("ck_page_restriction_page_restriction_mode")
        ),
        sa.ForeignKeyConstraint(
            ["page_id"],
            ["page.id"],
            name=op.f("fk_page_restriction_page_id_page"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_page_restriction")),
        sa.UniqueConstraint(
            "page_id", "mode", "principal_kind", "principal_id", name="uq_page_restriction_target"
        ),
    )
    op.create_index("ix_page_restriction_page_id", "page_restriction", ["page_id"], unique=False)
    op.create_table(
        "page_version",
        sa.Column("page_id", sa.Uuid(), nullable=False),
        sa.Column("number", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("front_matter", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("author_id", sa.Uuid(), nullable=True),
        sa.Column("message", sa.String(length=500), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["user.id"],
            name=op.f("fk_page_version_author_id_user"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["page_id"], ["page.id"], name=op.f("fk_page_version_page_id_page"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_page_version")),
        sa.UniqueConstraint("page_id", "number", name="uq_page_version_page_id_number"),
    )
    op.create_index("ix_page_version_page_id", "page_version", ["page_id"], unique=False)
    # ### end Alembic commands ###

    # 순환 참조라 autogenerate 가 못 만든다. 두 테이블이 다 생긴 뒤 붙인다.
    # 홈 문서를 휴지통으로 보내면 스페이스가 없는 문서를 가리키게 된다 —
    # SET NULL 로 스페이스는 살리고 홈만 비운다.
    op.create_foreign_key(
        op.f("fk_space_home_page_id_page"),
        "space",
        "page",
        ["home_page_id"],
        ["id"],
        ondelete="SET NULL",
    )


def downgrade() -> None:
    op.drop_constraint(op.f("fk_space_home_page_id_page"), "space", type_="foreignkey")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_page_version_page_id", table_name="page_version")
    op.drop_table("page_version")
    op.drop_index("ix_page_restriction_page_id", table_name="page_restriction")
    op.drop_table("page_restriction")
    op.drop_index("ix_page_label_label", table_name="page_label")
    op.drop_table("page_label")
    op.drop_index("ix_page_comment_parent_id", table_name="page_comment")
    op.drop_index("ix_page_comment_page_id", table_name="page_comment")
    op.drop_table("page_comment")
    op.drop_index("ix_page_template_space_id", table_name="page_template")
    op.drop_table("page_template")
    op.drop_index(
        "uq_page_space_root_slug", table_name="page", postgresql_where=sa.text("parent_id IS NULL")
    )
    op.drop_index(
        "uq_page_parent_slug", table_name="page", postgresql_where=sa.text("parent_id IS NOT NULL")
    )
    op.drop_index("ix_page_space_path", table_name="page")
    op.drop_index("ix_page_space_id", table_name="page")
    op.drop_index("ix_page_parent_id", table_name="page")
    op.drop_table("page")
    op.drop_table("space")
    # ### end Alembic commands ###
