"""issues core

Revision ID: d3324d645a0f
Revises: cd8b76292e18
Create Date: 2026-09-06 07:47:18.834106
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "d3324d645a0f"
down_revision: str | None = "cd8b76292e18"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "workflow",
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("is_builtin", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_workflow")),
        sa.UniqueConstraint("name", name=op.f("uq_workflow_name")),
    )
    op.create_table(
        "workflow_state",
        sa.Column("workflow_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("category", sa.String(length=16), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("is_initial", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "category IN ('todo', 'in_progress', 'done')",
            name=op.f("ck_workflow_state_workflow_state_category"),
        ),
        sa.ForeignKeyConstraint(
            ["workflow_id"],
            ["workflow.id"],
            name=op.f("fk_workflow_state_workflow_id_workflow"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_workflow_state")),
        sa.UniqueConstraint("workflow_id", "name", name="uq_workflow_state_workflow_id_name"),
    )
    op.create_index(
        "ix_workflow_state_workflow_id", "workflow_state", ["workflow_id"], unique=False
    )
    op.create_index(
        "uq_workflow_state_initial",
        "workflow_state",
        ["workflow_id"],
        unique=True,
        postgresql_where=sa.text("is_initial"),
    )
    op.create_table(
        "issue_category",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("default_assignee_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["default_assignee_id"],
            ["user.id"],
            name=op.f("fk_issue_category_default_assignee_id_user"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["project.id"],
            name=op.f("fk_issue_category_project_id_project"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_issue_category")),
        sa.UniqueConstraint("project_id", "name", name="uq_issue_category_project_id_name"),
    )
    op.create_table(
        "issue_type",
        sa.Column("project_id", sa.Uuid(), nullable=True),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("icon", sa.String(length=64), nullable=True),
        sa.Column("is_subtask", sa.Boolean(), nullable=False),
        sa.Column("workflow_id", sa.Uuid(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["project.id"],
            name=op.f("fk_issue_type_project_id_project"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workflow_id"],
            ["workflow.id"],
            name=op.f("fk_issue_type_workflow_id_workflow"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_issue_type")),
    )
    op.create_index("ix_issue_type_project_id", "issue_type", ["project_id"], unique=False)
    op.create_index("ix_issue_type_workflow_id", "issue_type", ["workflow_id"], unique=False)
    op.create_table(
        "security_level",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("grantees", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["project.id"],
            name=op.f("fk_security_level_project_id_project"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_security_level")),
        sa.UniqueConstraint("project_id", "name", name="uq_security_level_project_id_name"),
    )
    op.create_table(
        "version",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("start_date", sa.Date(), nullable=True),
        sa.Column("release_date", sa.Date(), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('open', 'released', 'archived')", name=op.f("ck_version_version_status")
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["project.id"],
            name=op.f("fk_version_project_id_project"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_version")),
        sa.UniqueConstraint("project_id", "name", name="uq_version_project_id_name"),
    )
    op.create_table(
        "workflow_transition",
        sa.Column("workflow_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("from_state_id", sa.Uuid(), nullable=True),
        sa.Column("to_state_id", sa.Uuid(), nullable=False),
        sa.Column("conditions", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("post_functions", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["from_state_id"],
            ["workflow_state.id"],
            name=op.f("fk_workflow_transition_from_state_id_workflow_state"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["to_state_id"],
            ["workflow_state.id"],
            name=op.f("fk_workflow_transition_to_state_id_workflow_state"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workflow_id"],
            ["workflow.id"],
            name=op.f("fk_workflow_transition_workflow_id_workflow"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_workflow_transition")),
    )
    op.create_index(
        "ix_workflow_transition_from_state_id",
        "workflow_transition",
        ["from_state_id"],
        unique=False,
    )
    op.create_index(
        "ix_workflow_transition_workflow_id", "workflow_transition", ["workflow_id"], unique=False
    )
    op.create_table(
        "field_definition",
        sa.Column("key", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("config", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("is_required", sa.Boolean(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=True),
        sa.Column("issue_type_id", sa.Uuid(), nullable=True),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "kind IN ('text', 'number', 'date', 'select', 'multi_select', 'user', 'version', 'bool', 'url')",
            name=op.f("ck_field_definition_field_definition_kind"),
        ),
        sa.CheckConstraint(
            "key = lower(key)", name=op.f("ck_field_definition_field_definition_key_lowercase")
        ),
        sa.ForeignKeyConstraint(
            ["issue_type_id"],
            ["issue_type.id"],
            name=op.f("fk_field_definition_issue_type_id_issue_type"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["project.id"],
            name=op.f("fk_field_definition_project_id_project"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_field_definition")),
        sa.UniqueConstraint("key", name=op.f("uq_field_definition_key")),
    )
    op.create_index(
        "ix_field_definition_scope",
        "field_definition",
        ["project_id", "issue_type_id"],
        unique=False,
    )
    op.create_table(
        "issue",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("key_seq", sa.Integer(), nullable=False),
        sa.Column("type_id", sa.Uuid(), nullable=False),
        sa.Column("state_id", sa.Uuid(), nullable=False),
        sa.Column("summary", sa.String(length=500), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("reporter_id", sa.Uuid(), nullable=True),
        sa.Column("assignee_id", sa.Uuid(), nullable=True),
        sa.Column("priority", sa.SmallInteger(), nullable=False),
        sa.Column("parent_id", sa.Uuid(), nullable=True),
        sa.Column("category_id", sa.Uuid(), nullable=True),
        sa.Column("fix_version_id", sa.Uuid(), nullable=True),
        sa.Column("security_level_id", sa.Uuid(), nullable=True),
        sa.Column("start_date", sa.Date(), nullable=True),
        sa.Column("due_date", sa.Date(), nullable=True),
        sa.Column("estimate_minutes", sa.Integer(), nullable=True),
        sa.Column("progress", sa.SmallInteger(), nullable=False),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("id <> parent_id", name=op.f("ck_issue_issue_parent_not_self")),
        sa.CheckConstraint("priority BETWEEN 1 AND 5", name=op.f("ck_issue_issue_priority_range")),
        sa.CheckConstraint(
            "progress BETWEEN 0 AND 100", name=op.f("ck_issue_issue_progress_range")
        ),
        sa.ForeignKeyConstraint(
            ["assignee_id"],
            ["user.id"],
            name=op.f("fk_issue_assignee_id_user"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["issue_category.id"],
            name=op.f("fk_issue_category_id_issue_category"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["fix_version_id"],
            ["version.id"],
            name=op.f("fk_issue_fix_version_id_version"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"], ["issue.id"], name=op.f("fk_issue_parent_id_issue"), ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["project.id"],
            name=op.f("fk_issue_project_id_project"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["reporter_id"],
            ["user.id"],
            name=op.f("fk_issue_reporter_id_user"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["security_level_id"],
            ["security_level.id"],
            name=op.f("fk_issue_security_level_id_security_level"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["state_id"],
            ["workflow_state.id"],
            name=op.f("fk_issue_state_id_workflow_state"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["type_id"],
            ["issue_type.id"],
            name=op.f("fk_issue_type_id_issue_type"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_issue")),
        sa.UniqueConstraint("project_id", "key_seq", name="uq_issue_project_id_key_seq"),
    )
    op.create_index("ix_issue_assignee_id", "issue", ["assignee_id"], unique=False)
    op.create_index("ix_issue_due_date", "issue", ["due_date"], unique=False)
    op.create_index("ix_issue_fix_version_id", "issue", ["fix_version_id"], unique=False)
    op.create_index("ix_issue_parent_id", "issue", ["parent_id"], unique=False)
    op.create_index(
        "ix_issue_project_state_updated",
        "issue",
        ["project_id", "state_id", "updated_at"],
        unique=False,
        postgresql_where=sa.text("archived_at IS NULL"),
    )
    op.create_index("ix_issue_reporter_id", "issue", ["reporter_id"], unique=False)
    op.create_index("ix_issue_security_level_id", "issue", ["security_level_id"], unique=False)
    op.create_index("ix_issue_type_id", "issue", ["type_id"], unique=False)
    op.create_table(
        "issue_comment",
        sa.Column("issue_id", sa.Uuid(), nullable=False),
        sa.Column("author_id", sa.Uuid(), nullable=True),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("is_internal", sa.Boolean(), nullable=False),
        sa.Column("edited_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["user.id"],
            name=op.f("fk_issue_comment_author_id_user"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["issue_id"],
            ["issue.id"],
            name=op.f("fk_issue_comment_issue_id_issue"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_issue_comment")),
    )
    op.create_index(
        "ix_issue_comment_issue_created",
        "issue_comment",
        ["issue_id", "created_at"],
        unique=False,
        postgresql_where=sa.text("archived_at IS NULL"),
    )
    op.create_table(
        "issue_field_value",
        sa.Column("issue_id", sa.Uuid(), nullable=False),
        sa.Column("field_key", sa.String(length=64), nullable=False),
        sa.Column("value", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(
            ["issue_id"],
            ["issue.id"],
            name=op.f("fk_issue_field_value_issue_id_issue"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("issue_id", "field_key", name=op.f("pk_issue_field_value")),
    )
    op.create_index(
        "ix_issue_field_value_gin",
        "issue_field_value",
        ["value"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index("ix_issue_field_value_key", "issue_field_value", ["field_key"], unique=False)
    op.create_table(
        "issue_history",
        sa.Column("issue_id", sa.Uuid(), nullable=False),
        sa.Column("actor_id", sa.Uuid(), nullable=True),
        sa.Column("changes", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["actor_id"],
            ["user.id"],
            name=op.f("fk_issue_history_actor_id_user"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["issue_id"],
            ["issue.id"],
            name=op.f("fk_issue_history_issue_id_issue"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_issue_history")),
    )
    op.create_index(
        "ix_issue_history_issue_created", "issue_history", ["issue_id", "created_at"], unique=False
    )
    op.create_table(
        "issue_label",
        sa.Column("issue_id", sa.Uuid(), nullable=False),
        sa.Column("label", sa.String(length=100), nullable=False),
        sa.ForeignKeyConstraint(
            ["issue_id"],
            ["issue.id"],
            name=op.f("fk_issue_label_issue_id_issue"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("issue_id", "label", name=op.f("pk_issue_label")),
    )
    op.create_index("ix_issue_label_label", "issue_label", ["label"], unique=False)
    op.create_table(
        "issue_link",
        sa.Column("from_issue_id", sa.Uuid(), nullable=False),
        sa.Column("to_issue_id", sa.Uuid(), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "kind IN ('blocks', 'relates', 'duplicates', 'precedes', 'copied')",
            name=op.f("ck_issue_link_issue_link_kind"),
        ),
        sa.CheckConstraint(
            "from_issue_id <> to_issue_id", name=op.f("ck_issue_link_issue_link_not_self")
        ),
        sa.ForeignKeyConstraint(
            ["from_issue_id"],
            ["issue.id"],
            name=op.f("fk_issue_link_from_issue_id_issue"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["to_issue_id"],
            ["issue.id"],
            name=op.f("fk_issue_link_to_issue_id_issue"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_issue_link")),
        sa.UniqueConstraint("from_issue_id", "to_issue_id", "kind", name="uq_issue_link_unique"),
    )
    op.create_index("ix_issue_link_from_issue_id", "issue_link", ["from_issue_id"], unique=False)
    op.create_index("ix_issue_link_to_issue_id", "issue_link", ["to_issue_id"], unique=False)
    op.create_table(
        "worklog",
        sa.Column("issue_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("spent_minutes", sa.Integer(), nullable=False),
        sa.Column("work_date", sa.Date(), nullable=False),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("spent_minutes > 0", name=op.f("ck_worklog_worklog_positive")),
        sa.ForeignKeyConstraint(
            ["issue_id"], ["issue.id"], name=op.f("fk_worklog_issue_id_issue"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["user.id"], name=op.f("fk_worklog_user_id_user"), ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_worklog")),
    )
    op.create_index("ix_worklog_issue_id", "worklog", ["issue_id"], unique=False)
    op.create_index("ix_worklog_user_work_date", "worklog", ["user_id", "work_date"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_worklog_user_work_date", table_name="worklog")
    op.drop_index("ix_worklog_issue_id", table_name="worklog")
    op.drop_table("worklog")
    op.drop_index("ix_issue_link_to_issue_id", table_name="issue_link")
    op.drop_index("ix_issue_link_from_issue_id", table_name="issue_link")
    op.drop_table("issue_link")
    op.drop_index("ix_issue_label_label", table_name="issue_label")
    op.drop_table("issue_label")
    op.drop_index("ix_issue_history_issue_created", table_name="issue_history")
    op.drop_table("issue_history")
    op.drop_index("ix_issue_field_value_key", table_name="issue_field_value")
    op.drop_index(
        "ix_issue_field_value_gin", table_name="issue_field_value", postgresql_using="gin"
    )
    op.drop_table("issue_field_value")
    op.drop_index(
        "ix_issue_comment_issue_created",
        table_name="issue_comment",
        postgresql_where=sa.text("archived_at IS NULL"),
    )
    op.drop_table("issue_comment")
    op.drop_index("ix_issue_type_id", table_name="issue")
    op.drop_index("ix_issue_security_level_id", table_name="issue")
    op.drop_index("ix_issue_reporter_id", table_name="issue")
    op.drop_index(
        "ix_issue_project_state_updated",
        table_name="issue",
        postgresql_where=sa.text("archived_at IS NULL"),
    )
    op.drop_index("ix_issue_parent_id", table_name="issue")
    op.drop_index("ix_issue_fix_version_id", table_name="issue")
    op.drop_index("ix_issue_due_date", table_name="issue")
    op.drop_index("ix_issue_assignee_id", table_name="issue")
    op.drop_table("issue")
    op.drop_index("ix_field_definition_scope", table_name="field_definition")
    op.drop_table("field_definition")
    op.drop_index("ix_workflow_transition_workflow_id", table_name="workflow_transition")
    op.drop_index("ix_workflow_transition_from_state_id", table_name="workflow_transition")
    op.drop_table("workflow_transition")
    op.drop_table("version")
    op.drop_table("security_level")
    op.drop_index("ix_issue_type_workflow_id", table_name="issue_type")
    op.drop_index("ix_issue_type_project_id", table_name="issue_type")
    op.drop_table("issue_type")
    op.drop_table("issue_category")
    op.drop_index(
        "uq_workflow_state_initial",
        table_name="workflow_state",
        postgresql_where=sa.text("is_initial"),
    )
    op.drop_index("ix_workflow_state_workflow_id", table_name="workflow_state")
    op.drop_table("workflow_state")
    op.drop_table("workflow")
    # ### end Alembic commands ###
