"""워커의 심장박동 (M4 운영)

워커가 죽으면 아무 일도 안 일어난다 — 알림도 메일도 웹훅도 SLA 클럭도
멈추는데 화면은 멀쩡하다. 마지막으로 **끝난** 시각을 한 줄로 남겨,
`/metrics` 와 `/readyz` 가 그것을 말할 수 있게 한다.

작업 이름이 PK 다. 이력이 아니라 지금 상태를 담는 표이고, 이력은 로그가 갖는다.


Revision ID: 3c0440c4a992
Revises: 54df8435a606
Create Date: 2026-09-07 23:31:04.141653
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "3c0440c4a992"
down_revision: str | None = "54df8435a606"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "heartbeat",
        sa.Column("task", sa.String(length=64), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("duration_seconds", sa.Float(), nullable=False),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("task", name=op.f("pk_heartbeat")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("heartbeat")
    # ### end Alembic commands ###
