"""app — 앱 등록과 확장 지점 (M6 "플러그인 훅")

`app` 이 등록된 앱, `app_slot` 이 그 앱이 화면에서 차지한 자리,
`app_panel` 이 앱이 이슈 하나에 써 둔 글이다.

**토큰은 해시로만 둔다.** 낼 때 한 번 보여 주고 우리는 잊는다(PAT 과 같은
규칙). 다시 볼 수 있게 두면 이 표가 비밀 창고가 되고, 목록을 읽는 사람이
모든 앱을 사칭할 수 있다.

`app.webhook_id` 가 **SET NULL** 인 이유: 서버 이벤트는 notify 의 웹훅이
서명·재시도·전송 로그까지 들고 있고(M2), 앱은 그것을 가리킬 뿐이다. 웹훅이
사라져도 앱과 그 자리는 남아야 한다 — 이벤트를 안 받고 패널만 쓰는 앱이
정당한 형태다.

`app_slot.kind` 에 CHECK 가 둘 붙는다. 어휘 하나(`link`·`panel`)와, 링크
자리는 주소가 있고 패널 자리는 없다는 것. 두 번째가 없으면 주소 없는 링크가
화면에 "아무 데도 안 가는 글자" 로 남는다.

`app_panel` 은 (자리, 이슈)가 곧 정체라서 따로 id 를 두지 않는다. 같은
이슈에 두 번 쓰면 덮어쓴다 — 지금 상태를 말하는 칸이고 이력이 아니다.
자리를 지우면 그 글도 함께 사라진다(CASCADE): 주인 없는 칸을 화면에 남기지
않는다.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "500b28d8682c"
down_revision: str | None = "7de774e3a762"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "app",
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("slug", sa.String(length=64), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("homepage_url", sa.String(length=2000), nullable=True),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("token_prefix", sa.String(length=16), nullable=False),
        sa.Column("webhook_id", sa.Uuid(), nullable=True),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by"], ["user.id"], name=op.f("fk_app_created_by_user"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["webhook_id"],
            ["webhook.id"],
            name=op.f("fk_app_webhook_id_webhook"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_app")),
        sa.UniqueConstraint("slug", name=op.f("uq_app_slug")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_app_token_hash")),
    )
    op.create_index(
        "ix_app_enabled", "app", ["enabled"], unique=False, postgresql_where=sa.text("enabled")
    )
    op.create_table(
        "app_slot",
        sa.Column("app_id", sa.Uuid(), nullable=False),
        sa.Column("slot", sa.String(length=64), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("label", sa.String(length=60), nullable=False),
        sa.Column("url_template", sa.String(length=2000), nullable=True),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(kind = 'link') = (url_template IS NOT NULL)",
            name=op.f("ck_app_slot_app_slot_url_matches_kind"),
        ),
        sa.CheckConstraint("kind IN ('link', 'panel')", name=op.f("ck_app_slot_app_slot_kind")),
        sa.ForeignKeyConstraint(
            ["app_id"], ["app.id"], name=op.f("fk_app_slot_app_id_app"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_app_slot")),
        sa.UniqueConstraint("app_id", "slot", "label", name="uq_app_slot_label"),
    )
    op.create_index("ix_app_slot_app_id", "app_slot", ["app_id"], unique=False)
    op.create_index("ix_app_slot_slot", "app_slot", ["slot"], unique=False)
    op.create_table(
        "app_panel",
        sa.Column("slot_id", sa.Uuid(), nullable=False),
        sa.Column("issue_id", sa.Uuid(), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["issue_id"], ["issue.id"], name=op.f("fk_app_panel_issue_id_issue"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["slot_id"],
            ["app_slot.id"],
            name=op.f("fk_app_panel_slot_id_app_slot"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("slot_id", "issue_id", name=op.f("pk_app_panel")),
    )
    op.create_index("ix_app_panel_issue", "app_panel", ["issue_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_app_panel_issue", table_name="app_panel")
    op.drop_table("app_panel")
    op.drop_index("ix_app_slot_slot", table_name="app_slot")
    op.drop_index("ix_app_slot_app_id", table_name="app_slot")
    op.drop_table("app_slot")
    op.drop_index("ix_app_enabled", table_name="app", postgresql_where=sa.text("enabled"))
    op.drop_table("app")
    # ### end Alembic commands ###
