export { ApiClient, type ClientOptions } from './client'
export { ApiError, isApiError, type ApiErrorBody } from './errors'
export { tokenStore, type TokenPair } from './tokens'
export {
  createAuthApi,
  type AuthApi,
  type CurrentUser,
  type SessionInfo,
  type TokenResponse,
  type TotpEnrollment,
  createUsersApi,
  type UserPage,
  type UsersApi,
} from './auth'
export {
  createProjectsApi,
  type NewProject,
  type Project,
  type ProjectPage,
  type ProjectsApi,
  createRolesApi,
  type PermissionDef,
  type RolesApi,
} from './projects'
export {
  createIssuesApi,
  type AvailableTransition,
  type FieldDefinition,
  type HistoryEntry,
  type Issue,
  type BulkEditResult,
  type BulkFailure,
  type IssueChanges,
  type IssueRelations,
  type RelatedIssue,
  type IssueComment,
  type IssuePage,
  type IssuePatch,
  type IssueSummary,
  type IssueType,
  type IssuesApi,
  type NewIssue,
  type TimeSummary,
  type WorkflowStateInfo,
  type Worklog,
  type WorklogPanel,
} from './issues'
export {
  createSearchApi,
  type IqlCatalog,
  type IqlError,
  type IqlFieldSpec,
  type IqlFunctionSpec,
  type IqlSuggestion,
  type IqlSuggestions,
  type IqlValidation,
  type SavedFilter,
  type SearchApi,
  type SearchHit,
  type SearchKind,
  type SuggestKind,
  type UnifiedSearchPage,
} from './search'
export {
  createBoardsApi,
  type Board,
  type BoardCard,
  type BoardColumnContent,
  type BoardColumnSpec,
  type BoardContent,
  type BoardPatch,
  type BoardsApi,
  type BoardSwimlane,
  type NewBoard,
  type SwimlaneField,
  SWIMLANE_FIELDS,
} from './boards'
export {
  createWikiApi,
  type CommentAnchor,
  type CommentMatch,
  type DiffLine,
  type LinkedPage,
  type NewPageTemplate,
  type NewPageComment,
  type NewSpace,
  type NewWikiPage,
  type PageComment,
  type PageDraft,
  type PageNode,
  type PageTemplate,
  type PageRestriction,
  type PageVersionDetail,
  type PageVersionSummary,
  type Space,
  type SpacePage,
  type VersionDiff,
  type WikiApi,
  type WikiPage,
  type WikiPagePatch,
} from './wiki'
export {
  createAttachmentsApi,
  type Attachment,
  type AttachmentsApi,
  type UploadTicket,
} from './attachments'
export {
  createApiTokensApi,
  type ApiToken,
  type ApiTokensApi,
  type IssuedApiToken,
} from './tokens-api'
